// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: mcs.proto

#pragma warning disable 1591, 0612, 3021
namespace McsProto
{

	[global::ProtoBuf.ProtoContract()]
	public partial class HeartbeatPing : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public HeartbeatPing()
		{
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(1, Name = @"stream_id")]
		public int StreamId
		{
			get { return __pbn__StreamId.GetValueOrDefault(); }
			set { __pbn__StreamId = value; }
		}
		public bool ShouldSerializeStreamId()
		{
			return __pbn__StreamId != null;
		}
		public void ResetStreamId()
		{
			__pbn__StreamId = null;
		}
		private int? __pbn__StreamId;

		[global::ProtoBuf.ProtoMember(2, Name = @"last_stream_id_received")]
		public int LastStreamIdReceived
		{
			get { return __pbn__LastStreamIdReceived.GetValueOrDefault(); }
			set { __pbn__LastStreamIdReceived = value; }
		}
		public bool ShouldSerializeLastStreamIdReceived()
		{
			return __pbn__LastStreamIdReceived != null;
		}
		public void ResetLastStreamIdReceived()
		{
			__pbn__LastStreamIdReceived = null;
		}
		private int? __pbn__LastStreamIdReceived;

		[global::ProtoBuf.ProtoMember(3, Name = @"status")]
		public long Status
		{
			get { return __pbn__Status.GetValueOrDefault(); }
			set { __pbn__Status = value; }
		}
		public bool ShouldSerializeStatus()
		{
			return __pbn__Status != null;
		}
		public void ResetStatus()
		{
			__pbn__Status = null;
		}
		private long? __pbn__Status;

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class HeartbeatAck : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public HeartbeatAck()
		{
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(1, Name = @"stream_id")]
		public int StreamId
		{
			get { return __pbn__StreamId.GetValueOrDefault(); }
			set { __pbn__StreamId = value; }
		}
		public bool ShouldSerializeStreamId()
		{
			return __pbn__StreamId != null;
		}
		public void ResetStreamId()
		{
			__pbn__StreamId = null;
		}
		private int? __pbn__StreamId;

		[global::ProtoBuf.ProtoMember(2, Name = @"last_stream_id_received")]
		public int LastStreamIdReceived
		{
			get { return __pbn__LastStreamIdReceived.GetValueOrDefault(); }
			set { __pbn__LastStreamIdReceived = value; }
		}
		public bool ShouldSerializeLastStreamIdReceived()
		{
			return __pbn__LastStreamIdReceived != null;
		}
		public void ResetLastStreamIdReceived()
		{
			__pbn__LastStreamIdReceived = null;
		}
		private int? __pbn__LastStreamIdReceived;

		[global::ProtoBuf.ProtoMember(3, Name = @"status")]
		public long Status
		{
			get { return __pbn__Status.GetValueOrDefault(); }
			set { __pbn__Status = value; }
		}
		public bool ShouldSerializeStatus()
		{
			return __pbn__Status != null;
		}
		public void ResetStatus()
		{
			__pbn__Status = null;
		}
		private long? __pbn__Status;

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class ErrorInfo : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public ErrorInfo()
		{
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(1, Name = @"code", IsRequired = true)]
		public int Code { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"message")]
		[global::System.ComponentModel.DefaultValue("")]
		public string Message
		{
			get { return __pbn__Message ?? ""; }
			set { __pbn__Message = value; }
		}
		public bool ShouldSerializeMessage()
		{
			return __pbn__Message != null;
		}
		public void ResetMessage()
		{
			__pbn__Message = null;
		}
		private string __pbn__Message;

		[global::ProtoBuf.ProtoMember(3, Name = @"type")]
		[global::System.ComponentModel.DefaultValue("")]
		public string Type
		{
			get { return __pbn__Type ?? ""; }
			set { __pbn__Type = value; }
		}
		public bool ShouldSerializeType()
		{
			return __pbn__Type != null;
		}
		public void ResetType()
		{
			__pbn__Type = null;
		}
		private string __pbn__Type;

		[global::ProtoBuf.ProtoMember(4, Name = @"extension")]
		public Extension Extension { get; set; }

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class Setting : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public Setting()
		{
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
		public string Name { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"value", IsRequired = true)]
		public string Value { get; set; }

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class HeartbeatStat : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public HeartbeatStat()
		{
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(1, Name = @"ip", IsRequired = true)]
		public string Ip { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"timeout", IsRequired = true)]
		public bool Timeout { get; set; }

		[global::ProtoBuf.ProtoMember(3, Name = @"interval_ms", IsRequired = true)]
		public int IntervalMs { get; set; }

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class HeartbeatConfig : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public HeartbeatConfig()
		{
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(1, Name = @"upload_stat")]
		public bool UploadStat
		{
			get { return __pbn__UploadStat.GetValueOrDefault(); }
			set { __pbn__UploadStat = value; }
		}
		public bool ShouldSerializeUploadStat()
		{
			return __pbn__UploadStat != null;
		}
		public void ResetUploadStat()
		{
			__pbn__UploadStat = null;
		}
		private bool? __pbn__UploadStat;

		[global::ProtoBuf.ProtoMember(2, Name = @"ip")]
		[global::System.ComponentModel.DefaultValue("")]
		public string Ip
		{
			get { return __pbn__Ip ?? ""; }
			set { __pbn__Ip = value; }
		}
		public bool ShouldSerializeIp()
		{
			return __pbn__Ip != null;
		}
		public void ResetIp()
		{
			__pbn__Ip = null;
		}
		private string __pbn__Ip;

		[global::ProtoBuf.ProtoMember(3, Name = @"interval_ms")]
		public int IntervalMs
		{
			get { return __pbn__IntervalMs.GetValueOrDefault(); }
			set { __pbn__IntervalMs = value; }
		}
		public bool ShouldSerializeIntervalMs()
		{
			return __pbn__IntervalMs != null;
		}
		public void ResetIntervalMs()
		{
			__pbn__IntervalMs = null;
		}
		private int? __pbn__IntervalMs;

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class LoginRequest : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public LoginRequest()
		{
			Settings = new global::System.Collections.Generic.List<Setting>();
			ReceivedPersistentIds = new global::System.Collections.Generic.List<string>();
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
		public string Id { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"domain", IsRequired = true)]
		public string Domain { get; set; }

		[global::ProtoBuf.ProtoMember(3, Name = @"user", IsRequired = true)]
		public string User { get; set; }

		[global::ProtoBuf.ProtoMember(4, Name = @"resource", IsRequired = true)]
		public string Resource { get; set; }

		[global::ProtoBuf.ProtoMember(5, Name = @"auth_token", IsRequired = true)]
		public string AuthToken { get; set; }

		[global::ProtoBuf.ProtoMember(6, Name = @"device_id")]
		[global::System.ComponentModel.DefaultValue("")]
		public string DeviceId
		{
			get { return __pbn__DeviceId ?? ""; }
			set { __pbn__DeviceId = value; }
		}
		public bool ShouldSerializeDeviceId()
		{
			return __pbn__DeviceId != null;
		}
		public void ResetDeviceId()
		{
			__pbn__DeviceId = null;
		}
		private string __pbn__DeviceId;

		[global::ProtoBuf.ProtoMember(7, Name = @"last_rmq_id")]
		public long LastRmqId
		{
			get { return __pbn__LastRmqId.GetValueOrDefault(); }
			set { __pbn__LastRmqId = value; }
		}
		public bool ShouldSerializeLastRmqId()
		{
			return __pbn__LastRmqId != null;
		}
		public void ResetLastRmqId()
		{
			__pbn__LastRmqId = null;
		}
		private long? __pbn__LastRmqId;

		[global::ProtoBuf.ProtoMember(8, Name = @"setting")]
		public global::System.Collections.Generic.List<Setting> Settings { get; private set; }

		[global::ProtoBuf.ProtoMember(10, Name = @"received_persistent_id")]
		public global::System.Collections.Generic.List<string> ReceivedPersistentIds { get; private set; }

		[global::ProtoBuf.ProtoMember(12, Name = @"adaptive_heartbeat")]
		public bool AdaptiveHeartbeat
		{
			get { return __pbn__AdaptiveHeartbeat.GetValueOrDefault(); }
			set { __pbn__AdaptiveHeartbeat = value; }
		}
		public bool ShouldSerializeAdaptiveHeartbeat()
		{
			return __pbn__AdaptiveHeartbeat != null;
		}
		public void ResetAdaptiveHeartbeat()
		{
			__pbn__AdaptiveHeartbeat = null;
		}
		private bool? __pbn__AdaptiveHeartbeat;

		[global::ProtoBuf.ProtoMember(13, Name = @"heartbeat_stat")]
		public HeartbeatStat HeartbeatStat { get; set; }

		[global::ProtoBuf.ProtoMember(14, Name = @"use_rmq2")]
		public bool UseRmq2
		{
			get { return __pbn__UseRmq2.GetValueOrDefault(); }
			set { __pbn__UseRmq2 = value; }
		}
		public bool ShouldSerializeUseRmq2()
		{
			return __pbn__UseRmq2 != null;
		}
		public void ResetUseRmq2()
		{
			__pbn__UseRmq2 = null;
		}
		private bool? __pbn__UseRmq2;

		[global::ProtoBuf.ProtoMember(15, Name = @"account_id")]
		public long AccountId
		{
			get { return __pbn__AccountId.GetValueOrDefault(); }
			set { __pbn__AccountId = value; }
		}
		public bool ShouldSerializeAccountId()
		{
			return __pbn__AccountId != null;
		}
		public void ResetAccountId()
		{
			__pbn__AccountId = null;
		}
		private long? __pbn__AccountId;

		[global::ProtoBuf.ProtoMember(16)]
		[global::System.ComponentModel.DefaultValue(AuthService.AndroidId)]
		public AuthService auth_service
		{
			get { return __pbn__auth_service ?? AuthService.AndroidId; }
			set { __pbn__auth_service = value; }
		}
		public bool ShouldSerializeauth_service()
		{
			return __pbn__auth_service != null;
		}
		public void Resetauth_service()
		{
			__pbn__auth_service = null;
		}
		private AuthService? __pbn__auth_service;

		[global::ProtoBuf.ProtoMember(17, Name = @"network_type")]
		public int NetworkType
		{
			get { return __pbn__NetworkType.GetValueOrDefault(); }
			set { __pbn__NetworkType = value; }
		}
		public bool ShouldSerializeNetworkType()
		{
			return __pbn__NetworkType != null;
		}
		public void ResetNetworkType()
		{
			__pbn__NetworkType = null;
		}
		private int? __pbn__NetworkType;

		[global::ProtoBuf.ProtoMember(18, Name = @"status")]
		public long Status
		{
			get { return __pbn__Status.GetValueOrDefault(); }
			set { __pbn__Status = value; }
		}
		public bool ShouldSerializeStatus()
		{
			return __pbn__Status != null;
		}
		public void ResetStatus()
		{
			__pbn__Status = null;
		}
		private long? __pbn__Status;

		[global::ProtoBuf.ProtoContract()]
		public enum AuthService
		{
			[global::ProtoBuf.ProtoEnum(Name = @"ANDROID_ID")]
			AndroidId = 2,
		}

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class LoginResponse : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public LoginResponse()
		{
			Settings = new global::System.Collections.Generic.List<Setting>();
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
		public string Id { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"jid")]
		[global::System.ComponentModel.DefaultValue("")]
		public string Jid
		{
			get { return __pbn__Jid ?? ""; }
			set { __pbn__Jid = value; }
		}
		public bool ShouldSerializeJid()
		{
			return __pbn__Jid != null;
		}
		public void ResetJid()
		{
			__pbn__Jid = null;
		}
		private string __pbn__Jid;

		[global::ProtoBuf.ProtoMember(3, Name = @"error")]
		public ErrorInfo Error { get; set; }

		[global::ProtoBuf.ProtoMember(4, Name = @"setting")]
		public global::System.Collections.Generic.List<Setting> Settings { get; private set; }

		[global::ProtoBuf.ProtoMember(5, Name = @"stream_id")]
		public int StreamId
		{
			get { return __pbn__StreamId.GetValueOrDefault(); }
			set { __pbn__StreamId = value; }
		}
		public bool ShouldSerializeStreamId()
		{
			return __pbn__StreamId != null;
		}
		public void ResetStreamId()
		{
			__pbn__StreamId = null;
		}
		private int? __pbn__StreamId;

		[global::ProtoBuf.ProtoMember(6, Name = @"last_stream_id_received")]
		public int LastStreamIdReceived
		{
			get { return __pbn__LastStreamIdReceived.GetValueOrDefault(); }
			set { __pbn__LastStreamIdReceived = value; }
		}
		public bool ShouldSerializeLastStreamIdReceived()
		{
			return __pbn__LastStreamIdReceived != null;
		}
		public void ResetLastStreamIdReceived()
		{
			__pbn__LastStreamIdReceived = null;
		}
		private int? __pbn__LastStreamIdReceived;

		[global::ProtoBuf.ProtoMember(7, Name = @"heartbeat_config")]
		public HeartbeatConfig HeartbeatConfig { get; set; }

		[global::ProtoBuf.ProtoMember(8, Name = @"server_timestamp")]
		public long ServerTimestamp
		{
			get { return __pbn__ServerTimestamp.GetValueOrDefault(); }
			set { __pbn__ServerTimestamp = value; }
		}
		public bool ShouldSerializeServerTimestamp()
		{
			return __pbn__ServerTimestamp != null;
		}
		public void ResetServerTimestamp()
		{
			__pbn__ServerTimestamp = null;
		}
		private long? __pbn__ServerTimestamp;

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class StreamErrorStanza : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public StreamErrorStanza()
		{
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
		public string Type { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"text")]
		[global::System.ComponentModel.DefaultValue("")]
		public string Text
		{
			get { return __pbn__Text ?? ""; }
			set { __pbn__Text = value; }
		}
		public bool ShouldSerializeText()
		{
			return __pbn__Text != null;
		}
		public void ResetText()
		{
			__pbn__Text = null;
		}
		private string __pbn__Text;

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class Close : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public Close()
		{
			OnConstructor();
		}

		partial void OnConstructor();

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class Extension : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public Extension()
		{
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
		public int Id { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"data", IsRequired = true)]
		public byte[] Data { get; set; }

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class IqStanza : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public IqStanza()
		{
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(1, Name = @"rmq_id")]
		public long RmqId
		{
			get { return __pbn__RmqId.GetValueOrDefault(); }
			set { __pbn__RmqId = value; }
		}
		public bool ShouldSerializeRmqId()
		{
			return __pbn__RmqId != null;
		}
		public void ResetRmqId()
		{
			__pbn__RmqId = null;
		}
		private long? __pbn__RmqId;

		[global::ProtoBuf.ProtoMember(2, Name = @"type", IsRequired = true)]
		public IqType Type { get; set; }

		[global::ProtoBuf.ProtoMember(3, Name = @"id", IsRequired = true)]
		public string Id { get; set; }

		[global::ProtoBuf.ProtoMember(4, Name = @"from")]
		[global::System.ComponentModel.DefaultValue("")]
		public string From
		{
			get { return __pbn__From ?? ""; }
			set { __pbn__From = value; }
		}
		public bool ShouldSerializeFrom()
		{
			return __pbn__From != null;
		}
		public void ResetFrom()
		{
			__pbn__From = null;
		}
		private string __pbn__From;

		[global::ProtoBuf.ProtoMember(5, Name = @"to")]
		[global::System.ComponentModel.DefaultValue("")]
		public string To
		{
			get { return __pbn__To ?? ""; }
			set { __pbn__To = value; }
		}
		public bool ShouldSerializeTo()
		{
			return __pbn__To != null;
		}
		public void ResetTo()
		{
			__pbn__To = null;
		}
		private string __pbn__To;

		[global::ProtoBuf.ProtoMember(6, Name = @"error")]
		public ErrorInfo Error { get; set; }

		[global::ProtoBuf.ProtoMember(7, Name = @"extension")]
		public Extension Extension { get; set; }

		[global::ProtoBuf.ProtoMember(8, Name = @"persistent_id")]
		[global::System.ComponentModel.DefaultValue("")]
		public string PersistentId
		{
			get { return __pbn__PersistentId ?? ""; }
			set { __pbn__PersistentId = value; }
		}
		public bool ShouldSerializePersistentId()
		{
			return __pbn__PersistentId != null;
		}
		public void ResetPersistentId()
		{
			__pbn__PersistentId = null;
		}
		private string __pbn__PersistentId;

		[global::ProtoBuf.ProtoMember(9, Name = @"stream_id")]
		public int StreamId
		{
			get { return __pbn__StreamId.GetValueOrDefault(); }
			set { __pbn__StreamId = value; }
		}
		public bool ShouldSerializeStreamId()
		{
			return __pbn__StreamId != null;
		}
		public void ResetStreamId()
		{
			__pbn__StreamId = null;
		}
		private int? __pbn__StreamId;

		[global::ProtoBuf.ProtoMember(10, Name = @"last_stream_id_received")]
		public int LastStreamIdReceived
		{
			get { return __pbn__LastStreamIdReceived.GetValueOrDefault(); }
			set { __pbn__LastStreamIdReceived = value; }
		}
		public bool ShouldSerializeLastStreamIdReceived()
		{
			return __pbn__LastStreamIdReceived != null;
		}
		public void ResetLastStreamIdReceived()
		{
			__pbn__LastStreamIdReceived = null;
		}
		private int? __pbn__LastStreamIdReceived;

		[global::ProtoBuf.ProtoMember(11, Name = @"account_id")]
		public long AccountId
		{
			get { return __pbn__AccountId.GetValueOrDefault(); }
			set { __pbn__AccountId = value; }
		}
		public bool ShouldSerializeAccountId()
		{
			return __pbn__AccountId != null;
		}
		public void ResetAccountId()
		{
			__pbn__AccountId = null;
		}
		private long? __pbn__AccountId;

		[global::ProtoBuf.ProtoMember(12, Name = @"status")]
		public long Status
		{
			get { return __pbn__Status.GetValueOrDefault(); }
			set { __pbn__Status = value; }
		}
		public bool ShouldSerializeStatus()
		{
			return __pbn__Status != null;
		}
		public void ResetStatus()
		{
			__pbn__Status = null;
		}
		private long? __pbn__Status;

		[global::ProtoBuf.ProtoContract()]
		public enum IqType
		{
			[global::ProtoBuf.ProtoEnum(Name = @"GET")]
			Get = 0,
			[global::ProtoBuf.ProtoEnum(Name = @"SET")]
			Set = 1,
			[global::ProtoBuf.ProtoEnum(Name = @"RESULT")]
			Result = 2,
			[global::ProtoBuf.ProtoEnum(Name = @"IQ_ERROR")]
			IqError = 3,
		}

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class AppData : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public AppData()
		{
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(1, Name = @"key", IsRequired = true)]
		public string Key { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"value", IsRequired = true)]
		public string Value { get; set; }

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class DataMessageStanza : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public DataMessageStanza()
		{
			AppDatas = new global::System.Collections.Generic.List<AppData>();
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(2, Name = @"id")]
		[global::System.ComponentModel.DefaultValue("")]
		public string Id
		{
			get { return __pbn__Id ?? ""; }
			set { __pbn__Id = value; }
		}
		public bool ShouldSerializeId()
		{
			return __pbn__Id != null;
		}
		public void ResetId()
		{
			__pbn__Id = null;
		}
		private string __pbn__Id;

		[global::ProtoBuf.ProtoMember(3, Name = @"from", IsRequired = true)]
		public string From { get; set; }

		[global::ProtoBuf.ProtoMember(4, Name = @"to")]
		[global::System.ComponentModel.DefaultValue("")]
		public string To
		{
			get { return __pbn__To ?? ""; }
			set { __pbn__To = value; }
		}
		public bool ShouldSerializeTo()
		{
			return __pbn__To != null;
		}
		public void ResetTo()
		{
			__pbn__To = null;
		}
		private string __pbn__To;

		[global::ProtoBuf.ProtoMember(5, Name = @"category", IsRequired = true)]
		public string Category { get; set; }

		[global::ProtoBuf.ProtoMember(6, Name = @"token")]
		[global::System.ComponentModel.DefaultValue("")]
		public string Token
		{
			get { return __pbn__Token ?? ""; }
			set { __pbn__Token = value; }
		}
		public bool ShouldSerializeToken()
		{
			return __pbn__Token != null;
		}
		public void ResetToken()
		{
			__pbn__Token = null;
		}
		private string __pbn__Token;

		[global::ProtoBuf.ProtoMember(7, Name = @"app_data")]
		public global::System.Collections.Generic.List<AppData> AppDatas { get; private set; }

		[global::ProtoBuf.ProtoMember(8, Name = @"from_trusted_server")]
		public bool FromTrustedServer
		{
			get { return __pbn__FromTrustedServer.GetValueOrDefault(); }
			set { __pbn__FromTrustedServer = value; }
		}
		public bool ShouldSerializeFromTrustedServer()
		{
			return __pbn__FromTrustedServer != null;
		}
		public void ResetFromTrustedServer()
		{
			__pbn__FromTrustedServer = null;
		}
		private bool? __pbn__FromTrustedServer;

		[global::ProtoBuf.ProtoMember(9, Name = @"persistent_id")]
		[global::System.ComponentModel.DefaultValue("")]
		public string PersistentId
		{
			get { return __pbn__PersistentId ?? ""; }
			set { __pbn__PersistentId = value; }
		}
		public bool ShouldSerializePersistentId()
		{
			return __pbn__PersistentId != null;
		}
		public void ResetPersistentId()
		{
			__pbn__PersistentId = null;
		}
		private string __pbn__PersistentId;

		[global::ProtoBuf.ProtoMember(10, Name = @"stream_id")]
		public int StreamId
		{
			get { return __pbn__StreamId.GetValueOrDefault(); }
			set { __pbn__StreamId = value; }
		}
		public bool ShouldSerializeStreamId()
		{
			return __pbn__StreamId != null;
		}
		public void ResetStreamId()
		{
			__pbn__StreamId = null;
		}
		private int? __pbn__StreamId;

		[global::ProtoBuf.ProtoMember(11, Name = @"last_stream_id_received")]
		public int LastStreamIdReceived
		{
			get { return __pbn__LastStreamIdReceived.GetValueOrDefault(); }
			set { __pbn__LastStreamIdReceived = value; }
		}
		public bool ShouldSerializeLastStreamIdReceived()
		{
			return __pbn__LastStreamIdReceived != null;
		}
		public void ResetLastStreamIdReceived()
		{
			__pbn__LastStreamIdReceived = null;
		}
		private int? __pbn__LastStreamIdReceived;

		[global::ProtoBuf.ProtoMember(13, Name = @"reg_id")]
		[global::System.ComponentModel.DefaultValue("")]
		public string RegId
		{
			get { return __pbn__RegId ?? ""; }
			set { __pbn__RegId = value; }
		}
		public bool ShouldSerializeRegId()
		{
			return __pbn__RegId != null;
		}
		public void ResetRegId()
		{
			__pbn__RegId = null;
		}
		private string __pbn__RegId;

		[global::ProtoBuf.ProtoMember(16, Name = @"device_user_id")]
		public long DeviceUserId
		{
			get { return __pbn__DeviceUserId.GetValueOrDefault(); }
			set { __pbn__DeviceUserId = value; }
		}
		public bool ShouldSerializeDeviceUserId()
		{
			return __pbn__DeviceUserId != null;
		}
		public void ResetDeviceUserId()
		{
			__pbn__DeviceUserId = null;
		}
		private long? __pbn__DeviceUserId;

		[global::ProtoBuf.ProtoMember(17, Name = @"ttl")]
		public int Ttl
		{
			get { return __pbn__Ttl.GetValueOrDefault(); }
			set { __pbn__Ttl = value; }
		}
		public bool ShouldSerializeTtl()
		{
			return __pbn__Ttl != null;
		}
		public void ResetTtl()
		{
			__pbn__Ttl = null;
		}
		private int? __pbn__Ttl;

		[global::ProtoBuf.ProtoMember(18, Name = @"sent")]
		public long Sent
		{
			get { return __pbn__Sent.GetValueOrDefault(); }
			set { __pbn__Sent = value; }
		}
		public bool ShouldSerializeSent()
		{
			return __pbn__Sent != null;
		}
		public void ResetSent()
		{
			__pbn__Sent = null;
		}
		private long? __pbn__Sent;

		[global::ProtoBuf.ProtoMember(19, Name = @"queued")]
		public int Queued
		{
			get { return __pbn__Queued.GetValueOrDefault(); }
			set { __pbn__Queued = value; }
		}
		public bool ShouldSerializeQueued()
		{
			return __pbn__Queued != null;
		}
		public void ResetQueued()
		{
			__pbn__Queued = null;
		}
		private int? __pbn__Queued;

		[global::ProtoBuf.ProtoMember(20, Name = @"status")]
		public long Status
		{
			get { return __pbn__Status.GetValueOrDefault(); }
			set { __pbn__Status = value; }
		}
		public bool ShouldSerializeStatus()
		{
			return __pbn__Status != null;
		}
		public void ResetStatus()
		{
			__pbn__Status = null;
		}
		private long? __pbn__Status;

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class StreamAck : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public StreamAck()
		{
			OnConstructor();
		}

		partial void OnConstructor();

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class SelectiveAck : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{
			return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
		}
		public SelectiveAck()
		{
			Ids = new global::System.Collections.Generic.List<string>();
			OnConstructor();
		}

		partial void OnConstructor();

		[global::ProtoBuf.ProtoMember(1, Name = @"id")]
		public global::System.Collections.Generic.List<string> Ids { get; private set; }

	}

}

#pragma warning restore 1591, 0612, 3021
